- hosts: localhost
  gather_facts: true
  vars:
    my_name: Chandan
  tasks:
#     - yum:
#         pkg: httpd
#         state: installed
#       when: ansible_distribution == "RedHat"
    
#     - apt:
#         pkg: apache2
#         state: installed
#       when: ansible_distribution == "Ubuntu"

    # Example that prints the loopback address and gateway for each host
    # - debug:
    #     msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
    #   when: ansible_product_uuid is defined

    - debug:
        msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
      when: ansible_default_ipv4.gateway is defined

    - shell: /usr/bin/uptime
      register: result

    - debug:
        var: result
    # - debug:
    #     msg: "{{ my_name }}"
    #   when: my_name == "Chandan1"

    # - name: Display all variables/facts known for a host
    #   debug:
    #     var: hostvars[inventory_hostname]

# - hosts: all
#   name: Setting up the hostnames
#   tasks:
#   - hostname: name="{{ inventory_hostname }}"
#     become: yes




# - hosts: webservers
#   gather_facts: false
#   name: Running group var debugs for webserver
#   tasks:
#    - debug: 
#       var: my_group_var

#    - name: Checking appserver groupvars in Webserver Hosts
#      debug:
#       var: appserver_groupvars
   
#    - pause: seconds=5

#    - debug:
#       var: webserver_groupvars

# - hosts: appservers
#   gather_facts: false
#   name: Running group var debugs for appservers
#   tasks:
#    - debug: 
#       var: my_group_var
#    - name: Checking Webservers groupvars in Appserver Hosts
#      debug:
#       var: appserver_groupvars

#    - pause: seconds=2

#    - debug:
#       var: webserver_groupvars



  
