- hosts: webservers
  vars:
    user_name: Chandan
  tasks:
    - template:
        src: example-template.j2
        dest: /tmp/jinta-output
    - debug: var=play_hosts

- hosts: webservers
  vars:
    user_name: Chandan
  tasks:
    - template:
        src: example-template-2.j2
        dest: /tmp/jinta-loop-output
