---
- hosts: webservers
  tasks:
  - name: Stop and remove nginx
    service: name=nginx state=stopped
  - name: Remove nginx package
    yum: name=nginx state=removed
  ignore_errors: yes


- hosts: webservers
  become: true
  roles:
    - ntp
    - httpd
    - deploy_static_content