---
# create new group, appservers, and install java
- hosts: webservers  # Host or Group of Selections
  gather_facts: true
  become: true
  vars:
    httpd_port: 8080
  tasks:
  
  - apt:
      pkg: apache2
      state: installed
    when: ansible_distribution == "RedHat" 

  - yum:
      pkg: httpd
      state: installed
    when: ansible_distribution == "RedHat"

  - yum:
      pkg: httpd
      state: installed
    when: ansible_distribution == "CentOS"

  - name: Start httpd
    service: name=apache2 state=started enabled=yes

- hosts: dbservers # Host or Group of Selections
  tasks:
  - name: Install Mysql web server # Naming the task for debug purpose
    yum: pkg=mysql state=installed  # Using module ( doing the task )
  

- hosts: appservers
  become: true
  tasks:
  - name: Install default-jdk
    yum: name=java-1.8.0-openjdk state=present
    when: ansible_os_family == "RedHat"
  - name: Install default-jdk for Debian
    apt: name=java-1.8.0-openjdk state=present
    when: ansible_os_family == "Debian"
  - name: Install java in amazon linux
    yum: name=java-1.8.0-openjdk state=present
    when: ansible_os_family == "Amazon"