- hosts: node01
  gather_facts: true
  vars:
    my_name: Chandan
  tasks:
    - yum:
        pkg: httpd
        state: installed
      when: ansible_distribution == "RedHat"

    - yum:
        pkg: httpd
        state: installed
      when: ansible_distribution == "Amazon"


    - apt:
        pkg: apache2
        state: installed
      when: ansible_distribution == "Ubuntu"

#    Example that prints the loopback address and gateway for each host
    - debug:
        msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
      when: ansible_product_uuid is defined

    - debug:
        msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
      when: ansible_default_ipv4.gateway is defined

    - shell: /usr/bin/uptime
      register: result

    - debug:
        var: result
        
    - debug:
        msg: "{{ my_name }}"
      when: my_name == "beCloudReady"

    - name: Display all variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname]
      

    - name: Display some varialbes variables/facts known for a host
      debug:
        var: hostvars[inventory_hostname].ansible_all_ipv4_addresses[0]
      # when: hostvars[inventory_hostname].ansible_all_ipv4_addresses[0] == "172.31.6.217"


- hosts: all
  name: Setting up the hostnames
  tasks:
  - hostname: name="{{ inventory_hostname }}"
    become: yes

- hosts: webservers
  gather_facts: false
  name: Running group var debugs for webserver
  tasks:
   - debug: 
      var: my_group_var

- hosts: dbserver
  gather_facts: false
  name: Running group var debugs for webserver
  tasks:
    - debug: var=testname
  

- hosts: appservers
  gather_facts: false
  name: Running group var debugs for appservers
  tasks:
    - debug: var=testname
