---
- name: Stops a kafka container
  ignore_errors: true
  docker_container:
    network_mode: host
    name: kafka
    image: 
    state: stopped
  tags: stop

- pause:
     seconds: 20

- name: Create a kafka container
  docker_container:
     network_mode: host
     name: kafka
     image:

     state: started
     restart_policy: always
     env:
     pull: yes
     ports:
      - "9096:9096"
      - "9999:9999"
      - "6667:6667"
      - "9092:9092"
  tags: start
